# Generated by Django 5.1.4 on 2024-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(choices=[(-1, 'Basement'), (1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Attic')])),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
    ]
